api:
  build: ../system/api
  container_name: api
  env_file: ./env
  ports:
    - "7000:7000"
frontend:
  build: ../system/frontend
  container_name: frontend
  env_file: ./env
  ports:
    - "6000:6000"
service-name:
  build: ../system/services/service-name
  container_name: service-name
  env_file: ./env
  ports:
    - "7001:7001"