api:
  build: ../services/api
  container_name: api
  env_file: ./env
  ports:
    - "7000:7000"
polyfill:
  build: ../services/polyfill
  container_name: polyfill
  env_file: ./env
  ports:
    - "6999:6999"
frontend:
  build: ../services/frontend
  container_name: frontend
  env_file: ./env
  ports:
    - "6000:6000"
service-name:
  build: ../services/service-name
  container_name: service-name
  env_file: ./env
  ports:
    - "6001:6001"